import json

# 完整的 100 条 Python 基础问答数据集
qa_data = [
    # 一、 基础概念与语法 (1-20)
    {"id": 1, "question": "Python 是什么类型的语言？", "answer": "Python 是一种解释型、面向对象、动态数据类型的高级程序设计语言。"},
    {"id": 2, "question": "Python 中如何单行注释？", "answer": "在 Python 中，使用井号（#）来进行单行注释。"},
    {"id": 3, "question": "Python 中如何多行注释？", "answer": "可以使用三个单引号 (''') 或三个双引号 (\"\"\") 将注释内容括起来实现多行注释。"},
    {"id": 4, "question": "什么是 Python 的缩进？", "answer": "Python 使用缩进（通常是4个空格）来表示代码块的分层结构，代替了其他语言中的大括号。"},
    {"id": 5, "question": "怎么查看 Python 的版本？", "answer": "在命令行输入 python --version 或在代码中导入 sys 模块后打印 sys.version。"},
    {"id": 6, "question": "Python 中有哪些基本数据类型？", "answer": "包括数字（Number）、字符串（String）、列表（List）、元组（Tuple）、集合（Set）和字典（Dictionary）。"},
    {"id": 7, "question": "Python 中如何声明一个变量？", "answer": "直接使用变量名加赋值号和值即可，例如：x = 10。Python 不需要显式声明变量类型。"},
    {"id": 8, "question": "什么是不可变数据类型？", "answer": "改变变量的值会导致分配新内存地址的数据类型，如数字、字符串、元组。"},
    {"id": 9, "question": "什么是可变数据类型？", "answer": "允许直接在原有内存地址上修改内容的数据类型，如列表、字典、集合。"},
    {"id": 10, "question": "如何将字符串转换为整数？", "answer": "使用内置的 int() 函数，例如 int(\"123\")。"},
    {"id": 11, "question": "如何将数字转换为字符串？", "answer": "使用内置的 str() 函数，例如 str(123)。"},
    {"id": 12, "question": "Python 中逻辑运算符有哪些？", "answer": "主要有 and（与）、or（或）、not（非）。"},
    {"id": 13, "question": "Python 中的布尔值是什么？", "answer": "布尔值有两个：True（真）和 False（假）。"},
    {"id": 14, "question": "什么是 Python 的关键字？", "answer": "关键字是 Python 内部保留的单词，不能用作变量名或函数名，如 if, else, def, class 等。"},
    {"id": 15, "question": "如何获取一个变量的数据类型？", "answer": "使用内置的 type() 函数，例如 type(x)。"},
    {"id": 16, "question": "如何检查一个变量是否是某种类型？", "answer": "推荐使用 isinstance(obj, type) 函数，例如 isinstance(x, int)。"},
    {"id": 17, "question": "print() 函数的作用是什么？", "answer": "用于向控制台或标准输出打印文本或变量的值。"},
    {"id": 18, "hidden_flag": "test", "question": "如何在 print() 中实现不换行输出？", "answer": "设置 end 参数为空字符串，例如 print(\"hello\", end=\"\")。"},
    {"id": 19, "question": "input() 函数的作用是什么？", "answer": "用于接收用户在控制台输入的数据，返回的结果一律是字符串类型。"},
    {"id": 20, "question": "什么是 Python 的三元运算符？", "answer": "Python 使用 X if 条件 else Y 的形式来实现条件赋值。"},

    # 二、 运算符与条件控制 (21-40)
    {"id": 21, "question": "Python 中的整除运算符是什么？", "answer": "是双斜杠 //，它返回商的整数部分。"},
    {"id": 22, "question": "Python 中的取余运算符是什么？", "answer": "是百分号 %，它返回除法的余数。"},
    {"id": 23, "question": "Python 中如何计算幂（次方）？", "answer": "使用双星号 ** 运算符，例如 2 ** 3 结果是 8。"},
    {"id": 24, "question": "== 和 is 有什么区别？", "answer": "== 比较两个对象的值是否相等，而 is 比较两个对象是否是同一个内存地址（即ID是否相同）。"},
    {"id": 25, "question": "Python 的条件分支语句结构是怎样的？", "answer": "结构为 if 条件: ... elif 条件: ... else: ...。"},
    {"id": 26, "question": "Python 中支持 switch-case 语句吗？", "answer": "Python 3.10 之前不支持，3.10 引入了类似于 switch 的 match-case 模式匹配语法。"},
    {"id": 27, "question": "什么是成员运算符？", "answer": "in 和 not in，用来判断一个元素是否存在于序列中。"},
    {"id": 28, "question": "while 循环的终止条件是什么？", "answer": "当 while 后面的条件表达式计算结果为 False 时循环终止。"},
    {"id": 29, "question": "for 循环一般用来做什么？", "answer": "用于遍历任何序列或可迭代对象（如列表、字符串、字典等）中的元素。"},
    {"id": 30, "question": "range() 函数怎么用？", "answer": "生成一个整数序列，常用于 for 循环。格式为 range(start, stop, step)。"},
    {"id": 31, "question": "break 关键字的作用是什么？", "answer": "用于立即跳出并终止当前所在的循环（for 或 while）。"},
    {"id": 32, "question": "continue 关键字的作用是什么？", "answer": "结束当前这一次循环迭代，直接跳入下一次循环的条件判断或迭代。"},
    {"id": 33, "question": "什么是循环中的 else 语句？", "answer": "当 for 或 while 循环正常结束（没有被 break 阻断）时执行的代码块。"},
    {"id": 34, "question": "如何创建一个空循环？", "answer": "在循环体中使用 pass 关键字占位，确保语法正确但不执行任何操作。"},
    {"id": 35, "question": "什么是死循环？", "answer": "循环条件永远为真的循环，例如 while True:，需要用 break 终止。"},
    {"id": 36, "question": "如何实现多重条件的复合判断？", "answer": "结合逻辑运算符使用，例如 if a > 0 and b < 10:。"},
    {"id": 37, "question": "赋值运算符有哪些简写形式？", "answer": "如 +=, -=, *=, /=, %=, **= 等，代表对变量自身进行运算并重新赋值。"},
    {"id": 38, "question": "什么是身份运算符？", "answer": "is 和 is not，用来评估两个对象是否指向同一块内存空间。"},
    {"id": 39, "question": "not 运算符有什么作用？", "answer": "布尔“非”操作，将 True 变为 False，将 False 变为 True。"},
    {"id": 40, "question": "如何在循环中同时获取索引和元素？", "answer": "使用 enumerate() 函数，例如 for i, val in enumerate(my_list):。"},

    # 三、 核心数据结构：列表、元组、字典与集合 (41-60)
    {"id": 41, "question": "如何创建一个空列表？", "answer": "使用方括号 my_list = [] 或内置函数 my_list = list()。"},
    {"id": 42, "question": "怎么向列表末尾添加一个元素？", "answer": "使用列表对象的 append() 方法，例如 my_list.append(item)。"},
    {"id": 43, "question": "append() 和 extend() 有什么区别？", "answer": "append() 把参数当作一个整体元素加入列表末尾；extend() 把可迭代参数中的元素逐个解包加入末尾。"},
    {"id": 44, "question": "列表怎么根据索引删除元素？", "answer": "可以使用 del my_list[index] 或者 my_list.pop(index)。"},
    {"id": 45, "question": "pop() 方法如果不传参数会怎样？", "answer": "默认删除并返回列表的最后一个元素。"},
    {"id": 46, "question": "列表如何根据值来删除元素？", "answer": "使用 remove(value) 方法，它会删除列表中第一个匹配该值的元素。"},
    {"id": 47, "question": "怎么获取列表的长度（元素个数）？", "answer": "使用内置函数 len(my_list)。"},
    {"id": 48, "question": "什么是列表切片？", "answer": "通过 list[start:stop:step] 的形式快速获取列表子集的操作。"},
    {"id": 49, "question": "怎么将列表倒序排列？", "answer": "使用 my_list.reverse() 原地反转，或使用切片 my_list[::-1]。"},
    {"id": 50, "question": "什么是列表推导式？", "answer": "一种从旧列表创建新列表的简洁写法，如 [x*2 for x in list]。"},
    {"id": 51, "question": "元组与列表最大的区别是什么？", "answer": "列表是可变的，而元组（Tuple）是一旦创建就不能修改的不可变序列。"},
    {"id": 52, "question": "怎么创建一个含有一个元素的元组？", "answer": "必须在元素后面加逗号，例如 my_tuple = (1,)。"},
    {"id": 53, "question": "如何创建一个空字典？", "answer": "使用大括号 my_dict = {} 或内置函数 dict()。"},
    {"id": 54, "question": "字典怎么添加或修改键值对？", "answer": "直接赋值，例如 my_dict['key'] = value。"},
    {"id": 55, "question": "字典获取键的值时，防报错的安全方法是什么？", "answer": "使用 my_dict.get('key', default_value)，键不存在时会返回默认值。"},
    {"id": 56, "question": "怎么获取字典所有的键和所有的值？", "answer": "键使用 my_dict.keys()，值使用 my_dict.values()。"},
    {"id": 57, "question": "怎么遍历字典的键值对？", "answer": "使用 my_dict.items()，例如 for k, v in my_dict.items():。"},
    {"id": 58, "question": "什么是集合（Set）？", "answer": "集合是一个无序的不重复元素序列，常用于去重和集合运算。"},
    {"id": 59, "question": "怎么向集合中添加元素？", "answer": "使用 my_set.add(element) 方法。"},
    {"id": 60, "question": "集合怎么求交集和并集？", "answer": "交集用 & 或 intersection()，并集用 | 或 union()。"},

    # 四、 字符串处理与常用内置函数 (61-80)
    {"id": 61, "question": "如何计算字符串中某个字符出现的次数？", "answer": "使用字符串的 count() 方法，例如 string.count('a')。"},
    {"id": 62, "question": "怎么检查字符串是否以某个子串开头或结尾？", "answer": "使用 startswith() 和 endswith() 方法。"},
    {"id": 63, "question": "如何将字符串中的大写字母转小写？", "answer": "使用字符串的 lower() 方法。"},
    {"id": 64, "question": "如何将字符串中的小写字母转大写？", "answer": "使用字符串的 upper() 方法。"},
    {"id": 65, "question": "怎么去掉字符串两端的空格？", "answer": "使用字符串的 strip() 方法。"},
    {"id": 66, "question": "如何替换字符串中的某一部分文本？", "answer": "使用 replace(old, new) 方法，例如 string.replace('a', 'b')。"},
    {"id": 67, "question": "怎么把字符串按照某个分隔符切分成列表？", "answer": "使用 split() 方法，例如 string.split(',')。"},
    {"id": 68, "question": "怎么把列表中的多个字符串拼接成一个完整的字符串？", "answer": "使用 join() 方法，例如 '-'.join(['a', 'b'])。"},
    {"id": 69, "question": "什么是格式化字符串 f-string？", "answer": "Python 3.6+ 引入的用 f\"text {variable}\" 快速嵌入变量的字符串格式化方法。"},
    {"id": 70, "question": "如何判断字符串是否全部由数字组成？", "answer": "使用 isdigit() 方法。"},
    {"id": 71, "question": "abs() 函数的作用是什么？", "answer": "计算并返回一个数字的绝对值。"},
    {"id": 72, "question": "max() 和 min() 函数怎么用？", "answer": "分别用于返回可迭代对象或多个参数中的最大值和最小值。"},
    {"id": 73, "question": "sum() 函数的作用是什么？", "answer": "对一个数字序列（如列表、元组）中的所有元素求和。"},
    {"id": 74, "question": "sorted() 函数和列表的 sort() 方法有什么区别？", "answer": "sort() 是列表的原地排序修改，而 sorted() 返回一个新的排好序的列表，不影响原数据。"},
    {"id": 75, "question": "zip() 函数的作用是什么？", "answer": "将多个可迭代对象打包成一个个由元组组成的聚合对象，便于同步遍历。"},
    {"id": 76, "question": "all() 函数什么时候返回 True？", "answer": "当可迭代对象中的所有元素都为真（或对象为空）时返回 True。"},
    {"id": 77, "question": "any() 函数什么时候返回 True？", "answer": "只要可迭代对象中有一个元素为真，就返回 True。"},
    {"id": 78, "question": "如何将一个十进制数字转换成二进制字符串？", "answer": "使用内置的 bin() 函数。"},
    {"id": 79, "question": "如何获取一个字符的 ASCII 码值？", "answer": "使用内置的 ord() 函数，例如 ord('A') 返回 65。"},
    {"id": 80, "question": "如何把 ASCII 码值转回对应的字符？", "answer": "使用内置的 chr() 函数，例如 chr(65) 返回 'A'。"},

    # 五、 函数、模块、文件与异常处理 (81-100)
    {"id": 81, "question": "Python 中如何定义一个函数？", "answer": "使用 def 关键字后跟函数名和参数列表，如 def my_func(param):。"},
    {"id": 82, "question": "什么是匿名函数 lambda？", "answer": "一种不需要显式命名的单行简易函数，格式为 lambda arg: expression。"},
    {"id": 83, "question": "函数的 return 语句有什么作用？", "answer": "用于结束函数的执行，并将结果返回给调用者。如果不写，默认返回 None。"},
    {"id": 84, "question": "什么是函数的形参和实参？", "answer": "形参是定义函数时声明的参数，实参是调用函数时实际传给函数的值。"},
    {"id": 85, "question": "什么是位置参数和关键字参数？", "answer": "位置参数根据传入顺序匹配，关键字参数通过 key=value 的形式指定名称匹配。"},
    {"id": 86, "hidden_flag": "test", "question": "函数内部怎么修改全局变量的值？", "answer": "需要在函数内部使用 global 关键字声明该变量。"},
    {"id": 87, "question": "什么是可变参数 *args？", "answer": "用于接收任意数量的非关键字（位置）参数，在函数内部组合为一个元组。"},
    {"id": 88, "question": "什么是可变参数 **kwargs？", "answer": "用于接收任意数量的关键字参数，在函数内部组合为一个字典。"},
    {"id": 89, "question": "如何导入一个外部模块？", "answer": "使用 import 语句，例如 import math 或 from math import sqrt。"},
    {"id": 90, "question": "import math 后怎么为模块起别名？", "answer": "使用 as 关键字，例如 import math as m。"},
    {"id": 91, "question": "__name__ == '__main__' 的作用是什么？", "answer": "用来判断当前脚本是被直接运行，还是被当作模块导入到其他脚本中。"},
    {"id": 92, "question": "如何以只读模式打开一个文本文件？", "answer": "使用 open('file.txt', 'r', encoding='utf-8')。"},
    {"id": 93, "question": "怎么往文件里写入内容？", "answer": "以写入模式（'w' 或 'a'）打开文件，然后调用文件对象的 write() 方法。"},
    {"id": 94, "question": "为什么推荐使用 with open(...) 语句操作文件？", "answer": "因为 with 语句（上下文管理器）能在操作完成后自动关闭文件，防止内存泄漏和文件损坏。"},
    {"id": 95, "question": "Python 中基础的异常处理结构是怎样的？", "answer": "使用 try...except... 结构来捕获并处理程序运行时的错误。"},
    {"id": 96, "question": "异常处理中的 finally 代码块有什么特点？", "answer": "无论 try 块中是否发生异常，finally 块中的代码都必定会被执行。"},
    {"id": 97, "question": "如何手动抛出一个异常？", "answer": "使用 raise 关键字后跟异常类，例如 raise ValueError(\"输入错误\")。"},
    {"id": 98, "question": "常见的 IndexError 是什么引起的？", "answer": "索引超出了序列（如列表、元组、字符串）的合法范围。"},
    {"id": 99, "question": "常见的 KeyError 是什么引起的？", "answer": "试图去访问字典中一个不存在的键（Key）。"},
    {"id": 100, "question": "什么是内置模块 os？", "answer": "os 模块提供了处理操作系统相关任务的功能，如操作文件路径、读取环境变量、创建文件夹等。"}
]

# 执行写入操作，把这 100 条问答存成 json 文件
with open('faq_dataset.json', 'w', encoding='utf-8') as f:
    json.dump(qa_data, f, ensure_ascii=False, indent=4)

print("【大功告成】100条基础问答数据集已经成功写入到 faq_dataset.json 中了！")